#
# Continuous integration config
# http://travis-ci.org/aduros/flambe

# wafl should support both Python versions
language: python
python:
    - 2.7
    - 3.2

# Install Haxe
before_script:
    - sudo apt-get install libgc1c2
    - curl http://haxe.org/file/hxinst-linux.tgz | tar zxf -
    - echo y | sudo ./hxinst-linux > /dev/null
    - echo | haxelib setup
    - haxelib install format
    - haxelib install nape

script: bin/run-travis
