#
# Continuous integration config
# http://travis-ci.org/aduros/flambe

# wafl should support both Python versions
language: python
python:
    - 2.6
    - 2.7
    - 3.2

# Install Haxe
before_script:
    - sudo add-apt-repository ppa:eyecreate/haxe -y
    - sudo apt-get update -y
    - sudo apt-get install haxe2 -y
    - mkdir -p ~/.haxe/lib
    - echo ~/.haxe/lib | haxelib setup
    - until haxelib install format 1.26; do sleep 1; done
    - until haxelib install nape; do sleep 1; done

script: bin/run-travis
